Update deploy-vue-storefront-cloud.yml
vuestorefront/sample-express-application pull request #1
Opened 2022-12-06 21:41 UTC by renanoliveira0

2022-12-07 16:20 UTC, Baroshem approved these changes

2022-12-07 16:23 UTC, nestak approved these changes

2022-12-08 00:33 UTC, renanoliveira0 commented
[vsf.atlassian.net/browse/PL-1364](https://vsf.atlassian.net/browse/PL-1364)

Attention, this PR adds breaking changes, it must be approved along with 2 other PRs and all must be deployed atomically, and tested immediately. This is not possible to do in advance, so it is necessary to observe who is responsible for deploying all the PRs and doing the tests.

Attention, the breaking change even breaks production, as it is the two templates that are changed, so the tests must be done in stage and then in production to validate and in case of any problem, the three PRs must be immediately reversed.

https://github.com/vuestorefront/platform-backend/pull/340
https://github.com/vuestorefront/sample-express-application-with-middleware/pull/2

2022-12-08 10:45 UTC, FRSgit approved these changes

2022-12-13 14:34 UTC, Frodigo requested changes

2022-12-13 14:34 UTC, Frodigo commented on .github/workflows/deploy-vue-storefront-cloud.yml
> +          node-version: "18.x"
It was requested to change the Node version from 12 to 14, not 18. So please change it to 14 to meet the requirements.

2022-12-13 14:45 UTC, renanoliveira0 commented on .github/workflows/deploy-vue-storefront-cloud.yml
> +          node-version: "18.x"
https://github.com/nodejs/Release

I figured the requirements were wrong as you can see from the link and the image.

Version 14 is at end of its life and the current LTS version is 18.

However, it's up to you to decide. Do you want me to leave it in version 14 anyway?

<img width="725" alt="image" src="https://user-images.githubusercontent.com/1081576/207363806-9a5c6e9e-fa89-4d3f-a6b7-6bdd80c5e900.png">

2022-12-13 14:53 UTC, Frodigo commented on .github/workflows/deploy-vue-storefront-cloud.yml
> +          node-version: "18.x"
Hi, @vuestorefront/integrations-team,

which version of Node is used in the eCommerce integrations? 

This repository is the sample Express template we used in the VSF Console when we bootstrap a new instance. 

Before this PR, there was Node 12. Should we update it to Node 14, 16, or 18? 

We want to use the Node version commonly used in the integrations.

2022-12-13 15:10 UTC, lsliwaradioluz commented on .github/workflows/deploy-vue-storefront-cloud.yml
> +          node-version: "18.x"
> which version of Node is used in the eCommerce integrations?

@Frodigo It's Node v16 or higher.

2022-12-13 15:28 UTC, Frodigo commented on .github/workflows/deploy-vue-storefront-cloud.yml
> +          node-version: "18.x"
@renanoliveira0 based on the comment above, can you change Node to Node 16?

2022-12-13 17:24 UTC, renanoliveira0 commented on .github/workflows/deploy-vue-storefront-cloud.yml
> +          node-version: "18.x"
Done: 5e8adf2d90aa7ab3001bb74ff5489e98c1aa0fbe

2022-12-13 17:27 UTC, renanoliveira0 commented
You can merge this PR here and it won't break anything. It closes this task: https://github.com/vuestorefront/sample-express-application/pull/1

Then we discussed open PR on the Platform/Console backend.

2022-12-14 05:53 UTC, Frodigo approved these changes

2022-12-14 05:53 UTC, merged